### ISSUE TITLE
How do you import fonts?

### ISSUE THREAD

**Issue by duezerouno** [bgian/static-starter#1]
Hi! Thank you for this. How do you usually import font-face? I am including the file in the public/fonts and in my css but I keep getting file:///fonts/PxGrotesk-Regular.woff net::ERR_FILE_NOT_FOUND - I am very new to Vue :)

**Comment by jsmmth** [comment]
So it's going to be different how ever you setup the project, but assuming you're using this with the css compiling down into public/css like I have it setup, then in your CSS make sure that you're referencing the correct font files, for example as your public folder contains:

fonts
css
js
Index.html
... etc

You'd have to go back a directory from your css. For example:

../fonts/PxGrotesk.... 

Although if you have it setup on a server where the public directory is reading as root, you could just simply do:

/fonts/...

I hope this helps ☺️

**Comment by jsmmth** [comment]
If that doesn't work, feel free to provide some code and I'd be happy to look through it ☺️

**Comment by duezerouno** [comment]
@JosephSmith127 hey thanks for the reply! Actually I had tried to go back a directory and the result when using ../fonts/ is this:

Uncaught Error: Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/PxGrotesk-Bold.woff' in '/Users/andrea/Websites/vue-tests/portfolio/assets/scss'

---
Also when I do this, a fonts folder is created in the main directory.

**Comment by duezerouno** [comment]
Also when I do this, a fonts folder is created in the main directory.

**Comment by duezerouno** [comment]
I am trying on a fresh clone of this repo

**Comment by jsmmth** [comment]
Ah! I tell you what it probably is, when compiling webpack looks for assets relative to the sass file. So say you're doing ../fonts/... then webpack will try look for assets/fonts/ files. But obviously thats not what we want!

in your webpack.mix.js file you can add the following lines of code:

``
mix.options({
   processCssUrls: false
});
``

This will stop webpack trying to find the font files, and compile. That way in your sass you can have the ../fonts/... directory, and as long as your fonts are there it should work :)

**Comment by jsmmth** [comment]
I have updated master with an example of what I said above, and it works for me including the font. Let me know if you have any further issues 😀

**Comment by duezerouno** [comment]
Works perfectly! Thank you 👍
